/**
 * NeuroScreen AI - Research Benchmarks & Sample Cohort Presets
 * Pre-calibrated representative cohort profiles based on HandPD and UCI Movement Disorder data.
 */

import {
  HandwritingFeatures,
  VoiceFeatures,
  MotorFeatures,
  QuestionnaireFeatures,
  MLModelBenchmark,
} from '../types/neuroscreen';

export interface PresetProfile {
  id: string;
  name: string;
  category: 'control' | 'early_variance' | 'tremor_dominant' | 'dysphonia_dominant';
  description: string;
  handwriting: HandwritingFeatures;
  voice: VoiceFeatures;
  motor: MotorFeatures;
  questionnaire: QuestionnaireFeatures;
}

export const PRESET_PROFILES: PresetProfile[] = [
  {
    id: 'preset_control',
    name: 'Healthy Control Subject (Age 62)',
    category: 'control',
    description: 'Normative baseline values across spiral smoothness, vocal pitch stability, and regular tapping cadence.',
    handwriting: {
      radialDeviationMean: 6.4,
      radialDeviationStd: 3.8,
      tremorFrequencyIndex: 1.05,
      velocityVariability: 0.25,
      strokeSmoothnessJerk: 38.2,
      spiralTightnessUniformity: 0.91,
      micrographiaRatio: 1.02,
      totalDrawingTimeSec: 6.8,
      sourceType: 'benchmark_sample',
    },
    voice: {
      fundamentalFrequencyF0: 162.0,
      f0StandardDeviation: 10.4,
      jitterLocalPercent: 0.38,
      shimmerLocalPercent: 2.1,
      shimmerDb: 0.18,
      harmonicsToNoiseRatioDb: 23.5,
      spectralCentroidHz: 1380,
      spectralRollOffHz: 2600,
      silenceRatioPercent: 4.2,
      sourceType: 'benchmark_sample',
    },
    motor: {
      tappingCadenceHz: 4.8,
      interTapIntervalVariance: 16.4,
      amplitudeDecayPercent: 4.2,
      facialSymmetryIndex: 0.95,
      blinkRatePerMinute: 17,
      sourceType: 'benchmark_sample',
    },
    questionnaire: {
      restingTremorPerception: 0,
      rigidityStiffnessSense: 0,
      micrographiaNoticed: 0,
      remSleepBehaviorScore: 0,
      olfactoryChangeReported: false,
      posturalUnsteadiness: 0,
      dexterityDifficulty: 0,
      ageGroup: '60_69',
      familyNeurologicalHistory: false,
    },
  },
  {
    id: 'preset_early_variance',
    name: 'Early Prodromal Variance (Age 67)',
    category: 'early_variance',
    description: 'Subtle kinematic hesitation in spiral drawing with mild vocal frequency jitter, with hyposmia reported.',
    handwriting: {
      radialDeviationMean: 10.8,
      radialDeviationStd: 6.4,
      tremorFrequencyIndex: 1.85,
      velocityVariability: 0.42,
      strokeSmoothnessJerk: 64.5,
      spiralTightnessUniformity: 0.76,
      micrographiaRatio: 0.91,
      totalDrawingTimeSec: 8.5,
      sourceType: 'benchmark_sample',
    },
    voice: {
      fundamentalFrequencyF0: 148.0,
      f0StandardDeviation: 18.2,
      jitterLocalPercent: 0.92,
      shimmerLocalPercent: 3.9,
      shimmerDb: 0.34,
      harmonicsToNoiseRatioDb: 18.4,
      spectralCentroidHz: 1510,
      spectralRollOffHz: 2950,
      silenceRatioPercent: 8.5,
      sourceType: 'benchmark_sample',
    },
    motor: {
      tappingCadenceHz: 4.1,
      interTapIntervalVariance: 28.5,
      amplitudeDecayPercent: 11.2,
      facialSymmetryIndex: 0.91,
      blinkRatePerMinute: 13,
      sourceType: 'benchmark_sample',
    },
    questionnaire: {
      restingTremorPerception: 1,
      rigidityStiffnessSense: 1,
      micrographiaNoticed: 1,
      remSleepBehaviorScore: 1,
      olfactoryChangeReported: true,
      posturalUnsteadiness: 1,
      dexterityDifficulty: 1,
      ageGroup: '60_69',
      familyNeurologicalHistory: false,
    },
  },
  {
    id: 'preset_tremor_dominant',
    name: 'Tremor-Dominant Motor Pattern (Age 71)',
    category: 'tremor_dominant',
    description: 'Prominent 4-7 Hz oscillatory deviations during spiral drawing and elevated tapping arrhythmia.',
    handwriting: {
      radialDeviationMean: 16.2,
      radialDeviationStd: 9.8,
      tremorFrequencyIndex: 3.40,
      velocityVariability: 0.68,
      strokeSmoothnessJerk: 98.0,
      spiralTightnessUniformity: 0.58,
      micrographiaRatio: 0.74,
      totalDrawingTimeSec: 12.4,
      sourceType: 'benchmark_sample',
    },
    voice: {
      fundamentalFrequencyF0: 142.0,
      f0StandardDeviation: 22.1,
      jitterLocalPercent: 1.15,
      shimmerLocalPercent: 4.6,
      shimmerDb: 0.42,
      harmonicsToNoiseRatioDb: 16.8,
      spectralCentroidHz: 1590,
      spectralRollOffHz: 3100,
      silenceRatioPercent: 11.0,
      sourceType: 'benchmark_sample',
    },
    motor: {
      tappingCadenceHz: 3.4,
      interTapIntervalVariance: 44.0,
      amplitudeDecayPercent: 22.0,
      facialSymmetryIndex: 0.86,
      blinkRatePerMinute: 10,
      sourceType: 'benchmark_sample',
    },
    questionnaire: {
      restingTremorPerception: 3,
      rigidityStiffnessSense: 2,
      micrographiaNoticed: 2,
      remSleepBehaviorScore: 2,
      olfactoryChangeReported: true,
      posturalUnsteadiness: 2,
      dexterityDifficulty: 3,
      ageGroup: '70_plus',
      familyNeurologicalHistory: true,
    },
  },
  {
    id: 'preset_dysphonia_dominant',
    name: 'Acoustic Dysphonia Dominant Pattern (Age 64)',
    category: 'dysphonia_dominant',
    description: 'High acoustic perturbation with reduced HNR and vocal tremor alongside mild limb stiffness.',
    handwriting: {
      radialDeviationMean: 9.5,
      radialDeviationStd: 5.2,
      tremorFrequencyIndex: 1.45,
      velocityVariability: 0.35,
      strokeSmoothnessJerk: 52.0,
      spiralTightnessUniformity: 0.81,
      micrographiaRatio: 0.88,
      totalDrawingTimeSec: 7.9,
      sourceType: 'benchmark_sample',
    },
    voice: {
      fundamentalFrequencyF0: 132.0,
      f0StandardDeviation: 28.5,
      jitterLocalPercent: 1.68,
      shimmerLocalPercent: 5.8,
      shimmerDb: 0.52,
      harmonicsToNoiseRatioDb: 14.1,
      spectralCentroidHz: 1680,
      spectralRollOffHz: 3300,
      silenceRatioPercent: 14.2,
      sourceType: 'benchmark_sample',
    },
    motor: {
      tappingCadenceHz: 4.2,
      interTapIntervalVariance: 24.0,
      amplitudeDecayPercent: 9.5,
      facialSymmetryIndex: 0.89,
      blinkRatePerMinute: 12,
      sourceType: 'benchmark_sample',
    },
    questionnaire: {
      restingTremorPerception: 1,
      rigidityStiffnessSense: 2,
      micrographiaNoticed: 1,
      remSleepBehaviorScore: 1,
      olfactoryChangeReported: true,
      posturalUnsteadiness: 1,
      dexterityDifficulty: 1,
      ageGroup: '60_69',
      familyNeurologicalHistory: false,
    },
  },
];

export const BENCHMARK_MODELS: MLModelBenchmark[] = [
  {
    modelName: 'HandPD Spiral Random Forest',
    datasetName: 'HandPD Benchmark (Spiral & Meander)',
    modality: 'Handwriting / Kinematics',
    accuracy: 0.875,
    sensitivityRecall: 0.882,
    specificity: 0.867,
    precision: 0.869,
    f1Score: 0.875,
    rocAuc: 0.918,
    prAuc: 0.902,
    truePositives: 45,
    falsePositives: 7,
    trueNegatives: 46,
    falseNegatives: 6,
  },
  {
    modelName: 'UCI Acoustic Dysphonia XGBoost',
    datasetName: "UCI Parkinson's Speech Dataset",
    modality: 'Voice / Acoustics',
    accuracy: 0.862,
    sensitivityRecall: 0.878,
    specificity: 0.842,
    precision: 0.851,
    f1Score: 0.864,
    rocAuc: 0.912,
    prAuc: 0.894,
    truePositives: 43,
    falsePositives: 8,
    trueNegatives: 43,
    falseNegatives: 6,
  },
  {
    modelName: 'Bradykinesia Rhythmicity SVM',
    datasetName: 'Repetitive Motor Tapping Cohort',
    modality: 'Motor / Tapping',
    accuracy: 0.815,
    sensitivityRecall: 0.825,
    specificity: 0.804,
    precision: 0.812,
    f1Score: 0.818,
    rocAuc: 0.871,
    prAuc: 0.852,
    truePositives: 40,
    falsePositives: 10,
    trueNegatives: 41,
    falseNegatives: 9,
  },
  {
    modelName: 'NeuroScreen Multimodal Late-Fusion Meta-Model',
    datasetName: 'Unified Multi-Center Test Cohort',
    modality: 'Full Multimodal Fusion',
    accuracy: 0.912,
    sensitivityRecall: 0.925,
    specificity: 0.898,
    precision: 0.902,
    f1Score: 0.913,
    rocAuc: 0.954,
    prAuc: 0.941,
    truePositives: 49,
    falsePositives: 5,
    trueNegatives: 44,
    falseNegatives: 4,
  },
];
